### ISSUE TITLE
Security Lock

### ISSUE THREAD

**Issue by dyaa** [yassirh/digitalocean-swimmer#35]
I think it's Urgent to make a security lock when i open the app i must enter the Pin Code to use the app.

**Comment by yassirh** [comment]
Seems like a good idea. but i still haven't figured out a good way to implement it. i'm open to suggestions.

**Comment by dyaa** [comment]
it can be like in this app https://play.google.com/store/apps/details?id=com.joshfng.basin

**Comment by shivasurya** [comment]
From API 23 you can utilize security service lock,I have done for one of my project may be I can help you?

**Comment by yassirh** [comment]
@shivasurya i would really like it if you make a pull request.

**Comment by shivasurya** [comment]
sure! i'll first read through the code and try to implement one,this weekend :) :+1:

**Comment by shivasurya** [comment]
@yassirh i'm getting problem while importing source code in  android studio - i followed the instructions - please help me.

**Comment by yassirh** [comment]
Sure what kind of errors did you get?
