### ISSUE TITLE
Add ssh key not working

### ISSUE THREAD

**Issue by haodong** [yassirh/digitalocean-swimmer#50]
Thanks for your software that now I could connect to mine. But the process is not as smooth as I expected. 

I use ssh key to directly login there for having no idea about the "password". When firstly I login from android ssh, which has already prepared a set of key, it just ignore my public key, even I have added it before through digital-ocean-swimmer. After my check, the mobile key is just appeared on the digital-ocean control panel, but not exist in my server.

I was just wondering if it is possible to add key into the server in order to login smoothly. Thanks again for your hard-working!

**Comment by yassirh** [comment]
Hi @haldong I have been busy lately so i m not making lot of progress on the app. but i will look into this request asap :)

**Comment by rolandstarke** [comment]
@haodong 
You mean add an ssh key to an already running server? There is no api for that.

**Comment by haodong** [comment]
Hi @rolandstarke , I mean add ssh key to a new deployed server. Is it possible? Or some mistake I've made?

**Comment by rolandstarke** [comment]
@haodong When you create a new dropplet you can select with ssh keys should be on that dropplet.
