### ISSUE TITLE
Contribution: missing file DigitalOceanSwimmer.properties

### ISSUE THREAD

**Issue by okaufmann** [yassirh/digitalocean-swimmer#53]
Hi,

After i forked your project to help yout out. I have a Problem with a gradle script. There should a file called `DigitalOceanSwimmer.properties` be loaded which is not included on github.

Its in the build.gradle file in the project root:

```java
Properties props = new Properties()
props.load(new FileInputStream(file(project.property("DigitalOceanSwimmer.properties"))))
```

Could you checkin an example or the original if the values are not protectable?

**Comment by yassirh** [comment]
@okaufmann i will make a small document to explain how to setup the project

**Comment by okaufmann** [comment]
Great Thanks :+1:

**Comment by yassirh** [comment]
@okaufmann Can you take a look and let me know if it is enough or more details are needed :)

**Comment by okaufmann** [comment]
It works now, not as you described but I'll extend the docs with the point I had Problems with.

Sorry for late answer.

**Comment by yassirh** [comment]
Great looking forward to your pull request :)

**Comment by okaufmann** [comment]
Here you are: https://github.com/yassirh/digitalocean-swimmer/pull/56
