### ISSUE TITLE
Flag for Bangalore1 missing

### ISSUE THREAD

**Issue by Strykar** [yassirh/digitalocean-swimmer#62]
The new location, Bangalore, is missing the flag of India. I see it's missing from yassirh/digitalocean-swimmer/tree/master/DigitalOceanSwimmer/src/main/res/drawable
Where are you getting the icons from, I'd submit a PR?
Here's a high-res set of free flag icons ISO named and zipped to 292 Kb http://www.famfamfam.com/lab/icons/flags

**Comment by yassirh** [comment]
I have fixed this on commit 1c7ecee8f9bcf4b6e9ecb12e5372b7ec1061aff5 thanks for the heads up
